### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by moookino** [Niduroki/docker-yourls-sqlite#1]
Hi @Niduroki 

I was struggling to run this image and was troubleshooting what's wrong on my side, then I realized folder for sqlite should be owned by www-data (chown -R www-data:www-data foldername), once ownership was changed everything works as expected.
I believe it worth mentioning as part of readme

Thanks for you work 👍🏻

**Comment by Niduroki** [comment]
I added a note about it, thanks for the heads-up.
